//export const requestURL="http://localhost:5000/"
export const requestURL="http://localhost:8080/"
const requests={
    fetchLogin:`login`,
    fetchJoinUp:`api/join-up`,
    fetchGetAccountInfo:`api/account`,
    fetchUpdateProfile:`api/setting/profile`,
    fetchUpdatePassword:`api/setting/password`,
    fetchGetMyJob:`api/setting/job`,
    fetchAddMyJobsTags:`api/setting/add/jobs`,
    fetchRemoveMyJobsTags:`api/setting/delete/jobs`,
    fetchGetMyLocation:`api/setting/zone`,
    fetchAddMyLocation:`api/setting/zone/add`,
    fetchRemoveMyLocation:`api/setting/zone/delete`,
    fetchAddWork:`api/work/add`,
    fetchGetWork:`api/work`,
    fetchWorkSetting:`api/work/setting`,
    fetchRecruitment:`api/recruitment`,
    fetchGetNotification:`api/notification`,
    sseNotify:`api/notify`,
    fetchSearch:`api/search/work`,
    fetchMainWork:`api/main/work`,
    fetchAdminWork:`api/account/work`,
    fetchGetMyNotification:`api/setting/my-notification`,
    fetchUpdateMyNotification:`api/setting/update/notifications`,
    fetchGetMyData:`api/main/my-data`,
    fetchReadNotification:`api/notification/read`,
    fetchReadAllNotification:`api/notification/read/all`,
    fetchDeleteOldNotification:`api/notification/remove/old`
}
//
// const requests={
//     fetchLogin:`${requestURL}login`,
//     fetchJoinUp:`${requestURL}api/join-up`,
//     fetchGetAccountInfo:`${requestURL}api/account`,
//     fetchUpdateProfile:`${requestURL}api/setting/profile`,
//     fetchUpdatePassword:`${requestURL}api/setting/password`,
//     fetchGetMyJob:`${requestURL}api/setting/job`,
//     fetchAddMyJobsTags:`${requestURL}api/setting/add/jobs`,
//     fetchRemoveMyJobsTags:`${requestURL}api/setting/delete/jobs`,
//     fetchGetMyLocation:`${requestURL}api/setting/zone`,
//     fetchAddMyLocation:`${requestURL}api/setting/zone/add`,
//     fetchRemoveMyLocation:`${requestURL}api/setting/zone/delete`,
//     fetchAddWork:`${requestURL}api/work/add`,
//     fetchGetWork:`${requestURL}api/work`,
//     fetchWorkSetting:`${requestURL}api/work/setting`,
//     fetchRecruitment:`${requestURL}api/recruitment`,
//     fetchGetNotification:`${requestURL}api/notification`,
//     sseNotify:`${requestURL}api/notify`,
//     fetchSearch:`${requestURL}api/search/work`,
//     fetchMainWork:`${requestURL}api/main/work`,
//     fetchAdminWork:`${requestURL}api/account/work`,
//     fetchGetMyNotification:`${requestURL}api/setting/my-notification`,
//     fetchUpdateMyNotification:`${requestURL}api/setting/update/notifications`,
//     fetchGetMyData:`${requestURL}api/main/my-data`,
//     fetchReadNotification:`${requestURL}api/notification/read`,
//     fetchReadAllNotification:`${requestURL}api/notification/read/all`,
//     fetchDeleteOldNotification:`${requestURL}api/notification/remove/old`
// }

export default requests;